name: Node.js 24/7 WhatsApp Bot Host

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 */4 * * *' # පැය 4න් 4ට Auto Restart වී නිරන්තරයෙන් Active තබයි

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install

    - name: Run WhatsApp Bot
      run: node index.js
